### ISSUE TITLE
How to create with create page? Not with simple model form

### ISSUE THREAD

**Issue by naingwin** [solutionforest/filament-tree#1]
How can I create with normal create form? Because I want to use localeSwitcher() for multiple translations. Or how can I use with "filament/spatie-laravel-translatable-plugin".

**Comment by cklei-carly** [comment]
Please use the trait `SolutionForest\FilamentTree\Concern\TreeRecords\Translatable`, then setup the action and the available locale just like the step of filament (https://filamentphp.com/docs/2.x/spatie-laravel-translatable-plugin/getting-started#preparing-your-resource-class)

![example](https://user-images.githubusercontent.com/68525320/235901907-3fdd292a-6648-47bb-9806-9dd8daf36140.png)
