### ISSUE TITLE
Any plans for a Filament v3 version

### ISSUE THREAD

**Issue by cheesegrits** [solutionforest/filament-tree#11]
Not an issue as such, just wondering if you are intending to release a Filament v3 version?

**Comment by lam0819** [comment]
We think it will default support already, we will see any issue when v3 is officially released.

**Comment by cheesegrits** [comment]
> We think it will default support already, we will see any issue when v3 is officially released.

Just FYI, I have a v3 branch of filament-tree I'm working on locally, and there are quite a few changes needed.
