### ISSUE TITLE
window.livewire.find is not a function

### ISSUE THREAD

**Issue by fvanzeijl** [solutionforest/filament-tree#14]
Hi,
I used this package as dependency with your Access-Management-Package.

But I can not save sorted states. If I click on save-button i get JS-Error:

```bash
window.livewire.find is not a function
```
This error located in `filament-tree/resources/views/scripts.blade.php` on Line 48.

(btw. there is a console.log, which should not be called in production)

**Comment by lam0819** [comment]
could you create a sample repository for us, we try to fix it.

and which browser , os you are testing?
