### ISSUE TITLE
How to make custom query? 

### ISSUE THREAD

**Issue by biscuitrainbow** [solutionforest/filament-tree#15]
I have to filter data before showing in the tree.

Are there any ways that achieve somethings similar to this ?

```
public static function getEloquentQuery(): Builder
{
  return parent::getEloquentQuery()->where('visible', true);
}
```

**Comment by biscuitrainbow** [comment]
I can achieve this using Eloquent global scope just for you. It do the job.
https://laravel.com/docs/10.x/eloquent#global-scopes

**Comment by jinbatsu** [comment]
Hello, sorry to reply closed post, where do you put the global scoupe?
How do you achieve it?

In my case I want to create 5 different scoupe.
Did you mean create additional Model for each, extend and add it to booted global scoupe?

EDITED: ok it solved my case, I create Base Model and use seperate Model, and seperate Widget, etc.

**Comment by flashmediasolutions** [comment]
For anyone that finds this:

Insert this into your widget

```
<?php
 
namespace App\Filament\Widgets;
 
use App\Models\ProductCategory as ModelsProductCategory;
use App\Filament\Widgets;
use Filament\Forms\Components\TextInput;
use SolutionForest\FilamentTree\Widgets\Tree as BaseWidget;
use Illuminate\Database\Eloquent\Builder; // <- ADDED THIS
 
class ProductCategoryWidget extends BaseWidget
{
    public ?Model $record = null; // <- ADDED THIS
    
    protected static string $model = ModelsProductCategory::class;
 
    // you can customize the maximum depth of your tree
    protected static int $maxDepth = 2;
 
    protected ?string $treeTitle = 'ProductCategory';
 
    protected bool $enableTreeTitle = true;
 
    protected function getFormSchema(): array
    {
        return [
            TextInput::make('title'),
        ];
    }
    
    public function getTreeQuery(): Builder  // <- ADDED THIS
    {
        return ModelsProductCategory::query()->where('your_custom_id', '=', $this->record->id);
    }
}
```

Obviously you can adjust the query to meet your needs.

This works for me. If there is a better way, I'd love to know.
