### ISSUE TITLE
Need SBS (step-by-step) documentation

### ISSUE THREAD

**Issue by mrezauli** [solutionforest/filament-tree#2]
1. if I generate only a page (without resource) then "SolutionForest\FilamentTree\Pages\TreePage::getTreeRecordTitle(): Return value must be of type string, null returned" is appeared
2. if I generate a page (with resource) then how do I access them with proper routing???
3. what about migration for model that needs tree

**Comment by sergeynilov** [comment]
Yes, I also would like to see some (step-by-step) documentation or maybe youtube on video? Can source of data be custom(not from 1 table) or from 2 tables(like category and items) >

Thank you!

**Comment by lam0819** [comment]
README updated.
