### ISSUE TITLE
Drag-to-Reorder Handle Coloring in "Dark Mode"

### ISSUE THREAD

**Issue by nxgcx** [solutionforest/filament-tree#21]
### Description
When Filament is running under "Dark Mode", the coloring looks out of place for the drag-to-reorder handles. It looks fine in light mode. There should probably also be some margin between the handle and the text next to it.

### Screenshots
<img width="1279" alt="image" src="https://github.com/solutionforest/filament-tree/assets/143533431/e3e285dd-de1c-4721-9190-037a1f5cfa96">

**Comment by krsaulitis-lmt** [comment]
This was fixed with this PR - https://github.com/solutionforest/filament-tree/pull/18. If you recently ugraded to Filament 3 run this command `php artisan filament:assets` and rebuild you assets.
