### ISSUE TITLE
Support filter , tab on tree

### ISSUE THREAD

**Issue by vantruong3289** [solutionforest/filament-tree#27]
I have tab language on table
I want tab still show on tree page
![image](https://github.com/solutionforest/filament-tree/assets/15699044/4eddfd67-edc0-40f4-afb8-3cbd44884864)
![image](https://github.com/solutionforest/filament-tree/assets/15699044/6796b279-4ab4-44dd-a1ee-6c03b7ff05ea)

**Comment by Hegabovic** [comment]
can you provide search and filter too in this enhancement ?

**Comment by lam0819** [comment]
I'm wondering if this original simple tree plugin is taking on too many tasks simultaneously.

**Comment by Hegabovic** [comment]
it is a pretty cool and useful package :D :rocket:

**Comment by Hegabovic** [comment]
where can i access those indicated in the attached screenshot ??? 

![Screenshot from 2023-11-21 10-34-54](https://github.com/solutionforest/filament-tree/assets/56083879/161854f3-b97b-49ce-ad4b-ba5273a3782c)

**Comment by lam0819** [comment]
no no , i mean 
Table library is official library
Tree library is our library

We will not combine two things into one.

**Comment by vantruong3289** [comment]
@lam0819 it always gets all the data despite filter.

**Comment by lam0819** [comment]
> it always gets all the data despite filter

not understand ?

if you mean you want a list of table, just use official table to show the list.
if you want to use tree layout , just use thirdparty library like this

**Comment by vantruong3289** [comment]
@lam0819 then I want this tree to have a filter filter like a table

**Comment by Hegabovic** [comment]
it would be great to make the tree widget has a toggle button to allow changing view from tree view to normal filament table view , i think this will be the ultimate perfection

**Comment by vantruong3289** [comment]
> it would be great to make the tree widget has a toggle button to allow changing view from tree view to normal filament table view , i think this will be the ultimate perfection

that's easy. Just add an action button.
The problem now is filter support

**Comment by Hegabovic** [comment]
> > it would be great to make the tree widget has a toggle button to allow changing view from tree view to normal filament table view , i think this will be the ultimate perfection
> 
> that's easy. Just add an action button. The problem now is filter support

can you provide a code snippet for it , i dont know to do it inside the widget

**Comment by vantruong3289** [comment]
@Hegabovic 
![image](https://github.com/solutionforest/filament-tree/assets/15699044/4be00c34-32dc-43c4-a243-4111e205a269)

**Comment by vantruong3289** [comment]
@lam0819 Can it support filter as table... as function filter 
![image](https://github.com/solutionforest/filament-tree/assets/15699044/71249b87-5c93-464b-86c6-3beb8dc368bb)
