### ISSUE TITLE
SolutionForest\FilamentTree\Support\Utils::buildNestedArray returns empty array when using null as parentId

### ISSUE THREAD

**Issue by btantlinger** [solutionforest/filament-tree#28]
I know the documentation recommends using -1, but,  I think it makes more sense to use use `null` as the value for the parentId field of root items.   Using null allows for simple parent() relationship, cascade deletes, etc because the parent_id column can be nullable.

Anyway, the tree component actually DOES work when using null for this value.  However, none of the functions in the ModelTree trait that rely on the Utils::buildNestedArray function work when using null. For example  treeNodes, selectArray all return empty arrays.

I believe one fix for this issue would be to modify the condition on line 62 of SolutionForest\FilamentTree\Support\Utils to check for a null parentId.  E.g changing the condtion to below, allows Utils::buildNestedArray to work with null.

```
if ( ($pk === $parentId) || ($pk === '' && $parentId === 0) ) {
```

**Comment by binaryfire** [comment]
+1 for this. Most apps use null when there shouldn’t be a parent relationship. Using -1 breaks compatibility with a lot of existing logic.

**Comment by fvanzeijl** [comment]
Just add `defaultParentKey()`-method to your model

```php
public static function defaultParentKey()
{
    return null;
}
```

**Comment by btantlinger** [comment]
Even with that method overridden in the model, Utils::buildNestedArray still returns an empty array.   Like I mentioned, null works for the tree component, but other methods in the ModelTree trait have issues.   

This is because line 52 of in Utils is using blank(), which null is.  

```
        if (blank($parentId)) {
            $parentId = self::defaultParentId();
        }
```


Then it's pulling the value from the config file on line 30, which if null is set in the config, it is getting cast to an int which is 0.

```
    public static function defaultParentId(): int
    {
        return (int) config('filament-tree.default_parent_id', -1);
    }
```


Thus, the fix is modifying line 62 of of SolutionForest\FilamentTree\Support\Utils like so:

```
if ( ($pk === $parentId) || ($pk === '' && $parentId === 0) ) {
```

**Comment by cklei-carly** [comment]
Thank you for your suggestion. I have made the necessary modifications to the `buildNestedArray` method in the `SolutionForest\FilamentTree\Support\Utils` class in version **2.0.7** to support cases where defaultParentKey() is null or other scenarios. 

However, please remember that you still need to modify the `defaultParentKey()` method for your specific model.
