### ISSUE TITLE
Should work with NULL parent_id

### ISSUE THREAD

**Issue by jawngee** [solutionforest/filament-tree#3]
You lose foreign key constraints with the -1 thing which is kind of no bueno.  Is there a reason it doesn't work with nulls?

**Comment by lam0819** [comment]
check https://github.com/solutionforest/filament-tree#prepare-the-database-and-model

we have hidden function  => defaultParentKey().
If you need to support your version, you can override it.

    // public static function defaultParentKey()
    // {
    //     return -1;
    // }

**Comment by RibesAlexandre** [comment]
Hi,

It can't works with null parent_id because of buildNestArray method with groupBy Method and defaultParentId method. 

You should inspire of https://github.com/staudenmeir/laravel-adjacency-list package to be more powerfull.

**Comment by lam0819** [comment]
i think it can be nullable if you need, but we prefer  making the thing more strict.for your need , you can make a migration change to be nullable.

Our approach is more simple than your suggestion library. we are not using nested set algo https://en.wikipedia.org/wiki/Nested_set_model
