### ISSUE TITLE
When Dragging and Dropping the tree element Save 

### ISSUE THREAD

**Issue by Hegabovic** [solutionforest/filament-tree#31]
is there a way to save on dropping the tree element ?

**Comment by fvanzeijl** [comment]
I dont recommend using view-overrides. But I think in this case there are no other ways to do this (without PR an update for that).

So you have to  publish the view-assets 
```bash
php artisan vendor:publish --tag="filament-tree-views"
```

Next step is to add the callback-method to the template
`resources/views/vendor/filament-tree/components/tree/index.blade.php`

Insert right after nestable is initiated:

```javascript
let nestedTree = $('#{{ $containerKey }}').nestable({
// ...

nestedTree.on('change', async function (e) {
  let value = $('#{{ $containerKey }}').nestable('serialize');
  let result = await @this.updateTree(value);
  
  if (result['reload'] === true) {
    @this.$refresh();
  }
})
```

**Comment by Hegabovic** [comment]
after i added it, it is not dragable anymore :D

**Comment by fvanzeijl** [comment]
Any js errors? Which version of filament you are using?

**Comment by Hegabovic** [comment]
filament version 3 
and no errors it is just  removed the concept of dragging and dropping

**Comment by fvanzeijl** [comment]
Can't reproduce, works very well on my site.
I customized the refresh-callback with livewire-refresh. Maybe you can use the original refresh-callback `window.location.reload();` from save-method?

```javascript
nestedTree.on('change', async function (e) {
  let value = $('#{{ $containerKey }}').nestable('serialize');
  let result = await @this.updateTree(value);

  if (result['reload'] === true) {
    window.location.reload();
  }
})
```
