### ISSUE TITLE
Max Depth not working - unable to make tree with more parents than 1

### ISSUE THREAD

**Issue by jakeofficial** [solutionforest/filament-tree#32]
Hello,
I tried the package and it works pretty well but even though i have my maxDepth set to 4 - im unable to drag&drop elements deeper than 1 parent. Looks like its just the JS that wont allow me to snap an element to the one that already has a parent. If i manually change the parent_id - it build the tree correctly and then allows me to snap to the child node.

**Comment by Hegabovic** [comment]
i tried it yesterday and it worked but not with overriding the static property no, i override the method responsible for the maxDepth and made it return the number of levels i wanted , and it worked just fine  

```
    /**
     * @param int $maxDepth
     */
    public static function setMaxDepth(int $maxDepth): void
    {
        self::$maxDepth = 99999;
    }
```

**Comment by cklei-carly** [comment]
Please upgrade to the new version 2.0.7 and re-publish assets using the command `php artisan filament:assets` to fix this issue
