### ISSUE TITLE
Use table-actions

### ISSUE THREAD

**Issue by fvanzeijl** [solutionforest/filament-tree#33]
Hey,

is there a way to use native table actions (for creating and editing).
I am building very complex forms that do not work well in a modal action.

**Comment by Hegabovic** [comment]
yes you can do that, by enabling the function hasView for example make it return true , and then use the confugureViewAction method override it then use URL to redirect to the normal page of your table action 

for example 
```
use Filament\Tables\Columns\TextColumn;
 
TextColumn::make('title')
    ->url(fn (Post $record): string => route('posts.edit', ['post' => $record]))
```

**Comment by fvanzeijl** [comment]
Thank you.

The problem is, I can not override the configureViewAction-method (or any other viewMethods) because it have to has the same declaration as it has in the BasePage-Class.

In short I can not change the type of the given action in the method, so the following code will end in declaration-error.

```php
use Filament\Tables\Actions\EditAction;

protected function configureEditAction(EditAction $action): EditAction
{
    return parent::configureEditAction($action)
        ->authorize(fn (Model $record): bool => static::getResource()::canEdit($record));
}
```

It has use the EditAction from
`SolutionForest\FilamentTree\Actions\EditAction` not the table-action (or any other native actions from filament)

**Comment by Hegabovic** [comment]
yes, but i think they are extending the same filament Action

**Comment by fvanzeijl** [comment]
Ah, finally I got it. 
Tried so hard to use native table-action. But I had to simple override the package-action.

```php
protected function configureEditAction(Actions\EditAction $action): Actions\EditAction {
  $action->link()->url(fn(Page $page) => route('filament.admin.resources.pages.edit', $page->id));
  return $action;
}
```

Thank you!
