### ISSUE TITLE
Cannot read properties of undefined (reading 'fn')

### ISSUE THREAD

**Issue by ufukseyithan** [solutionforest/filament-tree#41]
I am getting this error below outside the filament panel (in areas where I used custom forms):

![image](https://github.com/solutionforest/filament-tree/assets/29460896/b17ff811-6222-43fe-be06-468e121abaa4)

No idea why this happens. Anyone can help?

**Comment by cklei-carly** [comment]
See https://github.com/solutionforest/filament-tree/issues/51#issuecomment-2268727832
