### ISSUE TITLE
Javascript errors occur with the current filament version (v3.2.80), the plugin no longer works

### ISSUE THREAD

**Issue by mihob** [solutionforest/filament-tree#51]
The following Javascript errors occur with the current filament version:

<img width="856" alt="image" src="https://github.com/solutionforest/filament-tree/assets/48485580/5268774a-4baa-4103-8977-32f15d666af5">

<img width="849" alt="image" src="https://github.com/solutionforest/filament-tree/assets/48485580/28861a90-7542-4d8c-bb5f-dca80f4004e1">

The plugin no longer works.

**Comment by parse-code** [comment]
+1
have bug in spa mode, still work after force refresh the page

**Comment by xujinhui2015** [comment]
+1  I've been in this situation

**Comment by xujinhui2015** [comment]
My temporary solution is to disable the single page application mode for this URL.  
I hope the bug can be fixed.
```
->spaUrlExceptions(fn (): array => [
    MallGoodsCategoryResource::getUrl(),
])
```

**Comment by mihob** [comment]
The error I have described does not only occur in spa mode, but always.

The spa mode has never worked for me with this plugin.

**Comment by parse-code** [comment]
> The error I have described does not only occur in spa mode, but always.
> 
> The spa mode has never worked for me with this plugin.

disable spa works for me

**Comment by mihob** [comment]
Not for me

**Comment by sprtony** [comment]
Hi, Sorry for my english.
In my sutiation, the problem is with the funcion "$" and my solution was add

```
$ = jQuery;
```

in the view vendor/filament-tree/components/tree/index.blade.php before to initilizate the nestable

```
$ = jQuery;
let nestedTree = $('#{{ $containerKey }}').nestable({
    group: {{ $containerKey }},
    maxDepth: {{ $maxDepth }},
    expandBtnHTML: '',
    collapseBtnHTML: '',
});
```

**Comment by cklei-carly** [comment]
In version 2.1.0, we have removed some jQuery-related logic. Please upgrade to the latest version and check if the issue you were experiencing still occurs.
