### ISSUE TITLE
Incompatible with Spatie Translatable

### ISSUE THREAD

**Issue by mahallemuhtari** [solutionforest/filament-tree#54]
I use it with the Spatie Translatable ([https://filamentphp.com/plugins/filament-spatie-translatable](https://filamentphp.com/plugins/filament-spatie-translatable)) Plugin.

The problem is that this region does not change when the language changes.
<img width="1170" alt="Screenshot at Jun 11 01-34-53" src="https://github.com/solutionforest/filament-tree/assets/31033870/30547033-bc75-41fc-9c9a-9cf6ff491027">

Also, This is What This Place Looks Like.
<img width="1388" alt="Screenshot 2024-06-11 at 01 33 45" src="https://github.com/solutionforest/filament-tree/assets/31033870/b7e4d7b4-957d-43b4-8ca6-1849ab002620">

But it seems to work very well in the demo.
<img width="1328" alt="Screenshot at Jun 11 01-30-30" src="https://github.com/solutionforest/filament-tree/assets/31033870/44cf10d3-a949-41ed-89f6-5d6010d7290f">

**Comment by lam0819** [comment]
here is our demo https://github.com/solutionforest/filament-cms-website-plugin-demo
could you see what is the different?

**Comment by DevYSM** [comment]
Any solutions?

**Comment by cklei-carly** [comment]
Please reference the step of https://github.com/solutionforest/filament-tree/blob/2.x/README.md#translation.

More detail on https://github.com/solutionforest/filament-cms-website-plugin-demo/blob/main/src/app/Filament/Clusters/TreePlugin/Pages/MainMenuNavigation.php
