### ISSUE TITLE
How to load custom data fro filament-tree package?

### ISSUE THREAD

**Issue by PetroGromovo** [solutionforest/filament-tree#9]
On laravel 9 filamenphp site I need to show data in tree and I found this
https://github.com/solutionforest/filament-tree
plugin.

But source of this plugin is 1 table, not as in my case when I need to combine data from 3 sources and 2 of them are non related tables.
If there is a way to  load my custom data into this plugin?

I suppose it looks some laravel feature...
Has it any

        "filament/filament": "^2.17.39",
        "filament/forms": "^2.17.39",
        "laravel/framework": "^9.52.7",

Thanks in advance!

**Comment by skoro** [comment]
This plugin works with Eloquent models only, so you need to have a table. As a solution for your case, I would advise to use SQL VIEW to get the results of your complex query and the appropriate model for that view, the model only should have all the needed properties as that plugin requires: `parent_id`, `order`, `title` (they could be renamed in the config).

**Comment by lam0819** [comment]
you can try calebporzio's package 
https://github.com/calebporzio/sushi
or like @skoro say using a custom view in database.
